// scripts/names-batch-2.js
export const NAMES_BATCH_2 = [
    // People
    { id: "aaron-mosiah", name: "Aaron", type: "person", desc: "Son of Mosiah; missionary to the Lamanites.", refs: ["Alma 22"], pron: "AIR-un", img: "images/cards/default.webp" },
    { id: "omner", name: "Omner", type: "person", desc: "Son of Mosiah; missionary companion to Ammon.", refs: ["Alma 22"], pron: "OM-ner", img: "images/cards/default.webp" },
    { id: "himni", name: "Himni", type: "person", desc: "Son of Mosiah; preached among the Lamanites.", refs: ["Alma 23"], pron: "HIM-nigh", img: "images/cards/default.webp" },
    { id: "muloki", name: "Muloki", type: "person", desc: "Missionary companion of Aaron.", refs: ["Alma 20:2–3; 21:11"], pron: "moo-LOH-kee", img: "images/cards/default.webp" },
    { id: "ammah", name: "Ammah", type: "person", desc: "Missionary companion of Aaron.", refs: ["Alma 20:4; 21:11"], pron: "AM-uh", img: "images/cards/default.webp" },
    { id: "lamonis-queen", name: "Lamoni’s Queen", type: "person", desc: "Faithful queen who believed Ammon and was converted.", refs: ["Alma 19"], pron: "lah-MOH-nigh’s", img: "images/cards/default.webp" },
    { id: "abba", name: "Abish’s Father (converted)", type: "person", desc: "Father whose conversion story Abish remembered.", refs: ["Alma 19:16"], pron: "AY-bish", img: "images/cards/default.webp" },
    { id: "amalon", name: "Amalon", type: "person", desc: "Leader among the priests of Noah who oppressed Alma’s people.", refs: ["Mosiah 23–24"], pron: "AM-uh-lon", img: "images/cards/default.webp" },
    { id: "amulek-father", name: "Giddonah (Amulek’s father)", type: "person", desc: "Father of Amulek; same name as a chief judge.", refs: ["Alma 10:2"], pron: "gid-oh-NAY-uh", img: "images/cards/default.webp" },
    { id: "giddonah-judge", name: "Giddonah (judge)", type: "person", desc: "Chief judge in Gideon who sat with Alma.", refs: ["Alma 1:9–10"], pron: "gid-oh-NAY-uh", img: "images/cards/default.webp" },
    { id: "nephihah", name: "Nephihah", type: "person", desc: "Chief judge who succeeded Alma the Younger.", refs: ["Alma 4:17; 50:37"], pron: "NEE-fy-hah", img: "images/cards/default.webp" },
    { id: "pahoran-ii", name: "Pahoran II", type: "person", desc: "Son of Pahoran who became chief judge and was slain.", refs: ["Helaman 1:3–13"], pron: "pay-HO-ran", img: "images/cards/default.webp" },
    { id: "pacumeni", name: "Pacumeni", type: "person", desc: "Son of Pahoran who briefly served as chief judge.", refs: ["Helaman 1:5–13"], pron: "puh-KYOO-men-eye", img: "images/cards/default.webp" },
    { id: "paanchi", name: "Paanchi", type: "person", desc: "Son of Pahoran who sought the judgment seat and was condemned.", refs: ["Helaman 1:7–8"], pron: "pay-AN-chee", img: "images/cards/default.webp" },
    { id: "moronihah", name: "Moronihah", type: "person", desc: "Son of Captain Moroni; Nephite commander after his father.", refs: ["Alma 62:43; Helaman 4"], pron: "mo-row-nee-HAH", img: "images/cards/default.webp" },
    { id: "lehi-captain", name: "Lehi (Captain)", type: "person", desc: "Trusted military leader under Captain Moroni.", refs: ["Alma 49–51"], pron: "LEE-high", img: "images/cards/default.webp" },
    { id: "giddianhi", name: "Giddianhi", type: "person", desc: "Gadianton leader who threatened the Nephites.", refs: ["3 Nephi 3–4"], pron: "gid-ee-AN-high", img: "images/cards/default.webp" },
    { id: "gidgiddoni", name: "Gidgiddoni", type: "person", desc: "Righteous Nephite commander during Gadianton conflicts.", refs: ["3 Nephi 3:18–26"], pron: "gid-gid-DOH-nigh", img: "images/cards/default.webp" },
    { id: "lachoneus", name: "Lachoneus", type: "person", desc: "Chief judge who called the Nephites to repentance and defense.", refs: ["3 Nephi 3–4"], pron: "la-KOH-nee-us", img: "images/cards/default.webp" },
    { id: "lachoneus-ii", name: "Lachoneus II", type: "person", desc: "Chief judge slain by the Gadiantons prior to Christ’s coming.", refs: ["3 Nephi 7:1"], pron: "la-KOH-nee-us", img: "images/cards/default.webp" },
    { id: "nephi-helaman", name: "Nephi (son of Helaman)", type: "person", desc: "Prophet who performed miracles and preached repentance.", refs: ["Helaman 5–11"], pron: "NEE-figh", img: "images/cards/default.webp" },
    { id: "lehi-son-helaman", name: "Lehi (son of Helaman)", type: "person", desc: "Companion of Nephi; imprisoned and delivered miraculously.", refs: ["Helaman 5"], pron: "LEE-high", img: "images/cards/default.webp" },
    { id: "aminadab", name: "Aminadab", type: "person", desc: "Lamanite dissenter who helped prisoners remember how to pray.", refs: ["Helaman 5:35–41"], pron: "uh-MIN-uh-dab", img: "images/cards/default.webp" },
    { id: "timothy", name: "Timothy", type: "person", desc: "Disciple of Jesus who was raised from the dead.", refs: ["3 Nephi 19:4"], pron: "TIM-uh-thee", img: "images/cards/default.webp" },
    { id: "jonas", name: "Jonas", type: "person", desc: "Disciple chosen by the Savior in the Americas.", refs: ["3 Nephi 19:4"], pron: "JOH-nas", img: "images/cards/default.webp" },
    { id: "mathoni", name: "Mathoni", type: "person", desc: "One of the twelve disciples in 3 Nephi.", refs: ["3 Nephi 19:4"], pron: "muh-THOH-nigh", img: "images/cards/default.webp" },
    { id: "mathonihah", name: "Mathonihah", type: "person", desc: "One of the twelve disciples in 3 Nephi.", refs: ["3 Nephi 19:4"], pron: "muh-thoh-nee-HAH", img: "images/cards/default.webp" },
    { id: "nephi-disciple", name: "Nephi (disciple of Jesus)", type: "person", desc: "Disciple in 3 Nephi, not to be confused with earlier Nephi.", refs: ["3 Nephi 19:4"], pron: "NEE-figh", img: "images/cards/default.webp" },
    { id: "jesse", name: "Jesse (disciple)", type: "person", desc: "One of the twelve disciples of Jesus in the promised land.", refs: ["3 Nephi 19:4"], pron: "JESS-ee", img: "images/cards/default.webp" },
    { id: "isaac", name: "Isaac (disciple)", type: "person", desc: "One of the twelve disciples in 3 Nephi.", refs: ["3 Nephi 19:4"], pron: "EYE-zak", img: "images/cards/default.webp" },
    { id: "jacob-disciple", name: "Jacob (disciple)", type: "person", desc: "One of the twelve disciples in 3 Nephi.", refs: ["3 Nephi 19:4"], pron: "JAY-kub", img: "images/cards/default.webp" },
    { id: "amalekites", name: "Amalekites (people)", type: "person", desc: "A group aligned with Lamanites; opposed the Church.", refs: ["Alma 21:2–4"], pron: "uh-MAL-uh-kites", img: "images/cards/default.webp" },
    { id: "zoramites", name: "Zoramites (people)", type: "person", desc: "A dissenting group known for the Rameumptom prayer.", refs: ["Alma 31"], pron: "ZOR-uh-mites", img: "images/cards/default.webp" },
    { id: "moriancumer-man", name: "Moriancumer (man)", type: "person", desc: "Name of the brother of Jared given in later sources; noted here for study context.", refs: ["Ether 2–3"], pron: "mor-ee-AN-koo-mer", img: "images/cards/default.webp" },
    { id: "omer", name: "Omer", type: "person", desc: "Jaredite king who was warned to flee; father of Emer.", refs: ["Ether 8–9"], pron: "OH-mer", img: "images/cards/default.webp" },
    { id: "emer", name: "Emer", type: "person", desc: "Righteous Jaredite king; enjoyed a long, prosperous reign.", refs: ["Ether 9:15–22"], pron: "EE-mer", img: "images/cards/default.webp" },
    { id: "coriantor", name: "Coriantor", type: "person", desc: "Jaredite king and father of Ether.", refs: ["Ether 11:23"], pron: "kor-ee-AN-tor", img: "images/cards/default.webp" },
    { id: "lib-jaredite", name: "Lib (Jaredite)", type: "person", desc: "Jaredite king in a line of prosperity and defense.", refs: ["Ether 10:18–22"], pron: "LIB", img: "images/cards/default.webp" },
    { id: "hearthom", name: "Hearthom", type: "person", desc: "Jaredite king whose kingdom was taken; lived in captivity.", refs: ["Ether 10:30–31"], pron: "HAR-thum", img: "images/cards/default.webp" },
    { id: "heth", name: "Heth", type: "person", desc: "Jaredite king associated with secret combinations and famine.", refs: ["Ether 9:26–35"], pron: "HETH", img: "images/cards/default.webp" },
    { id: "com", name: "Com", type: "person", desc: "Jaredite ruler; fought robbers and secret combinations.", refs: ["Ether 10:31–34"], pron: "KAHM", img: "images/cards/default.webp" },
    { id: "shule", name: "Shule", type: "person", desc: "Jaredite king who regained the kingdom; upheld liberty.", refs: ["Ether 7:7–21"], pron: "SHOOL", img: "images/cards/default.webp" },
    { id: "orihah", name: "Orihah", type: "person", desc: "First Jaredite king, son of Jared.", refs: ["Ether 6:27"], pron: "OR-ee-hah", img: "images/cards/default.webp" },
    { id: "shared", name: "Shared", type: "person", desc: "Jaredite leader who contended with Coriantumr.", refs: ["Ether 14:8–16"], pron: "SHAI-erd", img: "images/cards/default.webp" },
    { id: "akish", name: "Akish", type: "person", desc: "Jaredite who formed secret combinations to gain power.", refs: ["Ether 8–9"], pron: "uh-KISH", img: "images/cards/default.webp" },
    { id: "amaron", name: "Amaron", type: "person", desc: "Nephite record keeper in the small plates line.", refs: ["Omni 1:3–4"], pron: "AM-uh-ron", img: "images/cards/default.webp" },
    { id: "chemish", name: "Chemish", type: "person", desc: "Record keeper who wrote briefly on the plates.", refs: ["Omni 1:8–9"], pron: "KEM-ish", img: "images/cards/default.webp" },
    { id: "abinom", name: "Abinadom", type: "person", desc: "Record keeper and father of Amaleki.", refs: ["Omni 1:10–11"], pron: "uh-BIN-uh-dum", img: "images/cards/default.webp" },
    { id: "helaman-ii", name: "Helaman II", type: "person", desc: "Son of Helaman; father of Nephi and Lehi.", refs: ["Helaman 3–4"], pron: "HEE-luh-man", img: "images/cards/default.webp" },
    { id: "nephi3", name: "Nephi (son of Nephi, disciple)", type: "person", desc: "Kept records at Christ’s coming; saw many signs.", refs: ["3 Nephi 1"], pron: "NEE-figh", img: "images/cards/default.webp" },
    { id: "ammonihah-sufferers", name: "Martyrs of Ammonihah", type: "person", desc: "Believers cast into fire who sealed their testimony.", refs: ["Alma 14:7–14"], pron: "am-uh-NIGH-huh", img: "images/cards/default.webp" },
    { id: "seantum", name: "Seantum", type: "person", desc: "Murderer exposed by Nephi through revelation.", refs: ["Helaman 9"], pron: "see-AN-tum", img: "images/cards/default.webp" },
    { id: "seezoram", name: "SeezoRam", type: "person", desc: "Chief judge slain by his brother Seantum.", refs: ["Helaman 9"], pron: "SEE-zo-ram", img: "images/cards/default.webp" },
    { id: "ammaron", name: "Ammaron", type: "person", desc: "Nephite who hid the records and instructed Mormon.", refs: ["Mormon 1:2–4"], pron: "AM-uh-ron", img: "images/cards/default.webp" },
    { id: "moron", name: "Moron (Jaredite)", type: "person", desc: "Jaredite king whose kingdom was taken by robbers.", refs: ["Ether 11:10–14"], pron: "MOH-ron", img: "images/cards/default.webp" },
    { id: "shez", name: "Shez", type: "person", desc: "Jaredite king who rebuilt the people after destruction.", refs: ["Ether 10:1–4"], pron: "SHEZ", img: "images/cards/default.webp" },
    { id: "riplakish", name: "Riplakish", type: "person", desc: "Jaredite king who taxed heavily; later overthrown.", refs: ["Ether 10:5–8"], pron: "RIP-lay-kish", img: "images/cards/default.webp" },
    { id: "gilead", name: "Gilead (Jaredite)", type: "person", desc: "Robber leader who sought the throne; was slain.", refs: ["Ether 14:9"], pron: "GIL-ee-ad", img: "images/cards/default.webp" },
    { id: "seth-jaredite", name: "Seth (Jaredite)", type: "person", desc: "Son of Shiblon who reigned in captivity.", refs: ["Ether 11:9"], pron: "SETH", img: "images/cards/default.webp" },
    { id: "esh", name: "Esrom", type: "person", desc: "Son of Omer; helped restore the kingdom.", refs: ["Ether 8–9"], pron: "EZ-rum", img: "images/cards/default.webp" },
    { id: "coriantum", name: "Coriantum", type: "person", desc: "Jaredite king; father of Com.", refs: ["Ether 9:25–26"], pron: "kor-ee-AN-tum", img: "images/cards/default.webp" },
    { id: "kish-jaredite", name: "Kish (Jaredite)", type: "person", desc: "Father of Corom in Jaredite genealogy.", refs: ["Ether 10:17–18"], pron: "KISH", img: "images/cards/default.webp" },

    // Places
    { id: "zarahemla-city", name: "Zarahemla (City)", type: "place", desc: "Capital city of the Nephites for many years.", refs: ["Mosiah 1–6; Alma 2"], pron: "zair-uh-HEM-luh", img: "images/cards/default.webp" },
    { id: "manti", name: "Manti (City)", type: "place", desc: "Strategic southern city in Nephite defenses.", refs: ["Alma 56–58"], pron: "MAN-tie", img: "images/cards/default.webp" },
    { id: "nephihah-city", name: "Nephihah (City)", type: "place", desc: "City fortified by Moroni; taken and retaken.", refs: ["Alma 50–51; 62"], pron: "NEE-fy-hah", img: "images/cards/default.webp" },
    { id: "moroni-city", name: "Moroni (City)", type: "place", desc: "City on the east sea; involved in later wars.", refs: ["Alma 50"], pron: "mo-ROW-nigh", img: "images/cards/default.webp" },
    { id: "lehi-city", name: "Lehi (City)", type: "place", desc: "City on the east sea near the city of Morianton.", refs: ["Alma 50"], pron: "LEE-high", img: "images/cards/default.webp" },
    { id: "bountiful-city", name: "Bountiful (City)", type: "place", desc: "Northern barrier city in Nephite defenses.", refs: ["Alma 50:32–34"], pron: "BOWN-tih-ful", img: "images/cards/default.webp" },
    { id: "antionum-city", name: "Antionum (City)", type: "place", desc: "Zoramite city tied to the Rameumptom.", refs: ["Alma 31"], pron: "an-tee-OH-num", img: "images/cards/default.webp" },
    { id: "antion", name: "Antion (Gold measure)", type: "term", desc: "Unit of measure for gold; appears in economic context.", refs: ["Alma 11:19"], pron: "AN-tee-on", img: "images/cards/default.webp" },
    { id: "hermounts", name: "Hermounts (Wilderness)", type: "place", desc: "Wilderness region where wild beasts roamed.", refs: ["Alma 2:36–38"], pron: "her-MOUNTS", img: "images/cards/default.webp" },
    { id: "east-wilderness", name: "East Wilderness", type: "place", desc: "Region along the east sea used in campaigns.", refs: ["Alma 50:9–12"], pron: "—", img: "images/cards/default.webp" },
    { id: "south-wilderness", name: "South Wilderness", type: "place", desc: "Frontier between Nephites and Lamanites.", refs: ["Alma 16:6–7"], pron: "—", img: "images/cards/default.webp" },
    { id: "west-sea", name: "West Sea", type: "place", desc: "Body of water forming Nephite geographical boundary.", refs: ["Alma 22:27"], pron: "—", img: "images/cards/default.webp" },
    { id: "east-sea", name: "East Sea", type: "place", desc: "Sea bordering eastern Nephite cities.", refs: ["Alma 50:13"], pron: "—", img: "images/cards/default.webp" },
    { id: "antipus", name: "Antipus (City/Region)", type: "place", desc: "Name associated with battles near the stripling warriors.", refs: ["Alma 56"], pron: "AN-tih-pus", img: "images/cards/default.webp" },
    { id: "mantis-wilderness", name: "Land near Manti (Wilderness)", type: "place", desc: "Area of ambush and maneuvering in stripling accounts.", refs: ["Alma 56–58"], pron: "—", img: "images/cards/default.webp" },
    { id: "noah-city", name: "Noah (City)", type: "place", desc: "City taken by Lamanites and later retaken by Nephites.", refs: ["Alma 49:12–16"], pron: "NO-uh", img: "images/cards/default.webp" },
    { id: "lehi-nephi-city", name: "Lehi-Nephi (City)", type: "place", desc: "City connected with Zeniff’s record.", refs: ["Mosiah 7–10"], pron: "LEE-high NEE-figh", img: "images/cards/default.webp" },
    { id: "shemlon-city", name: "Shemlon (City)", type: "place", desc: "City near Shilom; Lamanite location.", refs: ["Mosiah 10:7–8"], pron: "SHEM-lon", img: "images/cards/default.webp" },
    { id: "shilom-city", name: "Shilom (City)", type: "place", desc: "City restored by Zeniff; taxed by Noah.", refs: ["Mosiah 9–11"], pron: "SHY-lum", img: "images/cards/default.webp" },
    { id: "antionah-place", name: "Antionah (Place)", type: "place", desc: "Location in Ammonihah where Alma taught.", refs: ["Alma 12:20–21"], pron: "an-TYE-uh-nah", img: "images/cards/default.webp" },
    { id: "melek-land", name: "Land of Melek", type: "place", desc: "Region west of Sidon where Alma taught.", refs: ["Alma 8:3–4"], pron: "MEE-lek", img: "images/cards/default.webp" },
    { id: "jid", name: "Judea (City)", type: "place", desc: "City reinforced by Helaman and stripling warriors.", refs: ["Alma 56:9–15"], pron: "joo-DEE-uh", img: "images/cards/default.webp" },
    { id: "neenah", name: "Nephi (City/Land)", type: "place", desc: "Region southward associated with early Nephites.", refs: ["Mosiah 7–10"], pron: "NEE-figh", img: "images/cards/default.webp" },

    // Terms / Objects
    { id: "sword-of-laban", name: "Sword of Laban", type: "term", desc: "Weapon taken by Nephi; later a national relic.", refs: ["1 Nephi 4; Jacob 1:10"], pron: "—", img: "images/cards/default.webp" },
    { id: "plates-of-ether", name: "Plates of Ether", type: "term", desc: "Jaredite record discovered by the people of Limhi.", refs: ["Mosiah 8:9–13"], pron: "—", img: "images/cards/default.webp" },
    { id: "jaredite-stones", name: "Jaredite Stones", type: "term", desc: "Sixteen stones touched by the Lord to give light.", refs: ["Ether 3; 6:2–7"], pron: "—", img: "images/cards/default.webp" },
    { id: "seer-stones", name: "Seer Stones", type: "term", desc: "Instruments prepared to translate records (interpreters).", refs: ["Mosiah 28:11–16"], pron: "—", img: "images/cards/default.webp" },
    { id: "church-organization", name: "Organization of the Church", type: "term", desc: "Formation of Christ’s Church among the Nephites.", refs: ["3 Nephi 18; 26"], pron: "—", img: "images/cards/default.webp" },
    { id: "ordinances", name: "Ordinances (Nephite)", type: "term", desc: "Baptism and other ordinances taught by the Savior.", refs: ["3 Nephi 11, 18"], pron: "—", img: "images/cards/default.webp" },
    { id: "judges", name: "Reign of the Judges", type: "term", desc: "System replacing kings with elected judges.", refs: ["Mosiah 29"], pron: "—", img: "images/cards/default.webp" },
    { id: "chief-judge", name: "Chief Judge", type: "term", desc: "Highest civil office among the Nephites.", refs: ["Alma 4–50"], pron: "—", img: "images/cards/default.webp" },
    { id: "synagogues-zoramite", name: "Zoramite Synagogues", type: "term", desc: "Places of worship with the Rameumptom.", refs: ["Alma 31"], pron: "—", img: "images/cards/default.webp" },
    { id: "title-liberty-standard", name: "Standard of Liberty", type: "term", desc: "Banner raised to defend freedom and religion.", refs: ["Alma 46"], pron: "—", img: "images/cards/default.webp" },
    { id: "letter-moroni-pahoran", name: "Moroni’s Letter to Pahoran", type: "term", desc: "Rebuke and reconciliation over government support.", refs: ["Alma 60–61"], pron: "—", img: "images/cards/default.webp" },
    { id: "ziff", name: "Ziff (alloy)", type: "term", desc: "Material listed among Nephite metals.", refs: ["Mosiah 11:3"], pron: "ZIF", img: "images/cards/default.webp" },
    { id: "convert-covenant", name: "Covenant to Bury Weapons", type: "term", desc: "Promise of the Anti-Nephi-Lehies to never shed blood.", refs: ["Alma 24"], pron: "—", img: "images/cards/default.webp" },
    { id: "day-night-day", name: "Day, Night, and a Day (Sign)", type: "term", desc: "Sign of Christ’s birth among the Nephites.", refs: ["3 Nephi 1"], pron: "—", img: "images/cards/default.webp" },
    { id: "ministering-christ", name: "Christ’s Ministry Among Nephites", type: "term", desc: "Teachings, healings, and ordinations by Jesus Christ.", refs: ["3 Nephi 11–28"], pron: "—", img: "images/cards/default.webp" },
    { id: "eight-witnesses-type", name: "Three and Eight Witnesses (pattern)", type: "term", desc: "Witness patterns foreshadowed by scriptural practice.", refs: ["Ether 5:2–4"], pron: "—", img: "images/cards/default.webp" },
    { id: "deseret", name: "Deseret (Honeybee)", type: "term", desc: "Word meaning honeybee from Jaredite language.", refs: ["Ether 2:3"], pron: "DEZ-uh-ret", img: "images/cards/default.webp" },

    // More People (to push count high)
    { id: "antipas", name: "Antipus (Captain)", type: "person", desc: "Nephite military leader aided by Helaman’s warriors.", refs: ["Alma 56:9–51"], pron: "AN-tih-pus", img: "images/cards/default.webp" },
    { id: "gidgiddonah", name: "Gidgiddonah", type: "person", desc: "High priest among the people of Gideon.", refs: ["Alma 30:21"], pron: "gid-gid-DOH-nuh", img: "images/cards/default.webp" },
    { id: "ziniffites", name: "People of Zeniff", type: "person", desc: "Group who returned to possess the land of Nephi.", refs: ["Mosiah 9–22"], pron: "ZEN-if", img: "images/cards/default.webp" },
    { id: "lamanites-general", name: "Lamanites (general)", type: "person", desc: "Descendants of Laman and Lemuel and associated peoples.", refs: ["Throughout"], pron: "LAY-muh-nights", img: "images/cards/default.webp" },
    { id: "nephites-general", name: "Nephites (general)", type: "person", desc: "Those who followed Nephi and later allied groups.", refs: ["Throughout"], pron: "NEE-fites", img: "images/cards/default.webp" },
    { id: "amalekiahites", name: "Amalickiahites", type: "person", desc: "Followers of Amalickiah who opposed liberty.", refs: ["Alma 46–51"], pron: "uh-mal-ih-KYE-uh-ites", img: "images/cards/default.webp" },
    { id: "ammonites", name: "Ammonites (Anti-Nephi-Lehies)", type: "person", desc: "Converted Lamanites who covenanted for peace.", refs: ["Alma 23–27"], pron: "AM-uh-nites", img: "images/cards/default.webp" },
    { id: "moroniha-late", name: "Moronihah (late chief captain)", type: "person", desc: "Commanded during Nephite losses before Mormon.", refs: ["Helaman 4"], pron: "mo-row-nee-HAH", img: "images/cards/default.webp" },
    { id: "coriantumr-nephite", name: "Coriantumr (Nephite dissenter)", type: "person", desc: "Led Lamanite forces to take Zarahemla swiftly.", refs: ["Helaman 1:15–27"], pron: "kor-ee-AN-tum-er", img: "images/cards/default.webp" },
    { id: "ammoron-late", name: "Ammoron (Lamanite king)", type: "person", desc: "Brother of Amalickiah who continued the war.", refs: ["Alma 52–62"], pron: "AM-or-on", img: "images/cards/default.webp" },
    { id: "zoram-captain", name: "Zoram (captain)", type: "person", desc: "Lamanite leader who fought Teancum and Moroni.", refs: ["Alma 16:7–9"], pron: "ZOR-um", img: "images/cards/default.webp" },
    { id: "cumenihah", name: "Cumenihah", type: "person", desc: "Officer under Moroni; helped secure prisoners.", refs: ["Alma 57:28–30"], pron: "koo-MEN-ee-hah", img: "images/cards/default.webp" },
    { id: "haglund", name: "Lehonti", type: "person", desc: "Lamanite leader enticed down the mount by Amalickiah.", refs: ["Alma 47"], pron: "lay-HON-tie", img: "images/cards/default.webp" },
    { id: "morionton", name: "Morionton (man)", type: "person", desc: "Led a group northward; taught industry.", refs: ["Alma 50:29–36"], pron: "mor-ee-ON-ton", img: "images/cards/default.webp" },
    { id: "antionah-priest", name: "Antionah (high priest)", type: "person", desc: "Questioned Alma on resurrection.", refs: ["Alma 12"], pron: "an-TYE-uh-nah", img: "images/cards/default.webp" },
    { id: "zeezrom-convert", name: "Zeezrom (convert)", type: "person", desc: "Lawyer who repented and preached the gospel.", refs: ["Alma 15"], pron: "zee-ZEE-ruhm", img: "images/cards/default.webp" },

    // Additional Places & Terms to comfortably exceed 200 combined
    { id: "antionah-hill", name: "Hill Onidah", type: "place", desc: "Hill where Alma taught the poor Zoramites.", refs: ["Alma 32:4"], pron: "OH-nee-dah", img: "images/cards/default.webp" },
    { id: "onihah", name: "Onihah (City)", type: "place", desc: "City destroyed at Christ’s death.", refs: ["3 Nephi 9:7"], pron: "OH-nih-hah", img: "images/cards/default.webp" },
    { id: "jerusalem-lamanite", name: "Jerusalem (Lamanite land)", type: "place", desc: "City of Lamanites destroyed at Christ’s death.", refs: ["3 Nephi 9:7"], pron: "jer-OO-suh-lem", img: "images/cards/default.webp" },
    { id: "gid-city", name: "Gid (City)", type: "place", desc: "Prisoner exchange and stratagem locale.", refs: ["Alma 55"], pron: "GID", img: "images/cards/default.webp" },
    { id: "mulek-seaport", name: "Mulek (Seaport)", type: "place", desc: "Seaport city on the east sea.", refs: ["Alma 51–52"], pron: "MEW-lek", img: "images/cards/default.webp" },
    { id: "seer-office", name: "Seer, Translator, and Prophet (roles)", type: "term", desc: "Spiritual roles referenced with interpreters.", refs: ["Mosiah 8:13–18"], pron: "—", img: "images/cards/default.webp" },
    { id: "stripling-mothers", name: "Mothers’ Teachings of the Stripling Warriors", type: "term", desc: "Their faith sustained their sons in battle.", refs: ["Alma 56:47–48"], pron: "—", img: "images/cards/default.webp" },
    { id: "prison-ammonihah", name: "Ammonihah Prison", type: "place", desc: "Prison where Alma and Amulek were confined.", refs: ["Alma 14"], pron: "am-uh-NIGH-huh", img: "images/cards/default.webp" },
    { id: "waters-mormon", name: "Waters of Mormon (term)", type: "term", desc: "Baptismal site symbolic of covenant membership.", refs: ["Mosiah 18"], pron: "—", img: "images/cards/default.webp" },
    { id: "zenephi-record", name: "Record of Zeniff (term)", type: "term", desc: "Record folded into Mosiah narrative.", refs: ["Mosiah 9–10"], pron: "—", img: "images/cards/default.webp" },
    { id: "land-bountiful-old", name: "Old World Bountiful", type: "place", desc: "Place where Nephi built the ship.", refs: ["1 Nephi 17"], pron: "BOWN-tih-ful", img: "images/cards/default.webp" },
    { id: "irons-rod", name: "Rod of Iron (vision)", type: "term", desc: "Symbol in Lehi’s and Nephi’s visions representing the word of God.", refs: ["1 Nephi 8; 11–15"], pron: "—", img: "images/cards/default.webp" },
    { id: "tree-life", name: "Tree of Life (vision)", type: "term", desc: "Visionary symbol of God’s love and the Atonement.", refs: ["1 Nephi 8; 11"], pron: "—", img: "images/cards/default.webp" },
    { id: "great-and-spacious", name: "Great and Spacious Building", type: "term", desc: "Prideful world in Lehi’s and Nephi’s visions.", refs: ["1 Nephi 8; 11"], pron: "—", img: "images/cards/default.webp" },
    { id: "river-filthy-water", name: "Filthy River (vision)", type: "term", desc: "Part of Lehi’s dream separating the faithful.", refs: ["1 Nephi 8; 12:16"], pron: "—", img: "images/cards/default.webp" },
    { id: "mists-darkness", name: "Mists of Darkness", type: "term", desc: "Symbol of temptations and confusion.", refs: ["1 Nephi 8:23"], pron: "—", img: "images/cards/default.webp" },
    { id: "plates-small-large", name: "Small vs Large Plates", type: "term", desc: "Two Nephite record sets with different purposes.", refs: ["1 Nephi 9"], pron: "—", img: "images/cards/default.webp" },
    { id: "lamanite-queen", name: "Lamanite Queen (Lamoni’s mother)", type: "person", desc: "Received the gospel after Lamoni’s conversion.", refs: ["Alma 22"], pron: "—", img: "images/cards/default.webp" },
    { id: "korihor-end", name: "Korihor’s Death", type: "term", desc: "He was trampled after being struck dumb.", refs: ["Alma 30:59"], pron: "—", img: "images/cards/default.webp" },
    { id: "nephi-imprisonment", name: "Imprisonment of Nephi and Lehi", type: "term", desc: "Miraculous deliverance with fire and a cloud of darkness dispersed.", refs: ["Helaman 5"], pron: "—", img: "images/cards/default.webp" },
    { id: "zarahemla-tower", name: "Tower in Zarahemla", type: "term", desc: "King Benjamin addressed his people from a tower.", refs: ["Mosiah 2"], pron: "—", img: "images/cards/default.webp" },
    { id: "almas-baptisms", name: "Waters of Mormon Baptisms", type: "term", desc: "Formation of the Church under Alma the Elder.", refs: ["Mosiah 18"], pron: "—", img: "images/cards/default.webp" }
];
